site:
  title: Zot Docs
  start_page: antora-ui-default::index.adoc 
content:
  sources: 
  - url: https://github.com/project-zot/docs-zot.git
    branches: HEAD
  - url: https://github.com/project-zot/site-zot.git
    branches: [main]
    start_path: docs
ui: 
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files:
      - .nojekyll
  - path: .nojekyll

